apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: behvs02gl-nodejs 
  janus-idp.io/tekton: behvs02gl-nodejs
  backstage.io/kubernetes-id: behvs02gl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: behvs02gl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  